services:
  - type: web
    name: cv-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: cv-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: cv-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cv-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: cv-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: "5000"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        value: "https://ozan-yurdakul.onrender.com"

  - type: web
    name: ozan-yurdakul
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        value: "https://cv-backend-8gpl.onrender.com"

databases:
  - name: cv-db
    plan: free
